version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: encurtador_url_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: encurtador
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: encurtador_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/encurtador
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: encurtador_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge